### ISSUE TITLE
Tracking the file descriptor leaks issues

### ISSUE THREAD

**Issue by moyodiallo** [ocurrent/solver-service#46]
This is for tracking the current file descriptor leaks issues:
- [X] the pipes are not close after a child process finished its job and solved by this PR #39.
- [x] Using the git-unix during the update of `opam-repository` and that could be solved by this PR https://github.com/mirage/ocaml-git/pull/590
- [x] When we are getting the oldest opam-repository commit after doing a solve, we can end-up with lot pipes opened at same time. This is PR #47  that is supposed to solve it.
- [X] close the all unused file descriptors opened by git-unix #49 

cc @tmcgilchrist

**Comment by moyodiallo** [comment]
After the merge of this PR #49, we can revert https://github.com/ocurrent/ocaml-ci/pull/742 (upgrade solver/solver-ci and ocaml-ci/solver-ci submodule https://github.com/ocurrent/ocaml-ci/pull/757).

This is already stress tested :+1: 

@tmcgilchrist  @maiste @mtelvers
